name: Deploy K8s

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:
    
jobs:
  terrafrom:
    permissions:
      id-token: write
      contents: read

    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::498818051972:role/local-k8s-tfstate-role
          role-session-name: samplerolesession
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Decode terraform.tfvars from secret
        run: |
          echo "${{ secrets.TFVARS_B64 }}" > terraform.tfvars
      
      - name: Plan
        run: terraform init && terraform plan -out tfplan

      - name: Apply
        run: terraform apply --auto-approve tfplan